networks:
  camagru_network:
    driver: bridge

services:
  # Full nginx reverse proxy server
  server:
    container_name: server
    networks:
      - camagru_network
    build:
      context: ./server/docker
      dockerfile: ./Dockerfile
    image: server
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_healthy

  # JavaScript frontend application
  app:
    container_name: app
    networks:
      - camagru_network
    build:
      context: ./app/docker
      dockerfile: ./Dockerfile
    image: app
    expose:
      - 8080
    volumes:
      - ./app/src:/var/www/html:ro

  db:
    # Mariadb database
    container_name: db
    networks:
      - camagru_network
    build:
      context: ./db/docker
      dockerfile: ./Dockerfile
    image: db
    expose:
      - 3306
    env_file:
      - ./.env
    healthcheck:
      test: "mariadb-admin ping -p${DB_ROOT_PASSWD}"
      retries: 10
      interval: 2s

  api:
    # Php REST api
    container_name: api
    networks:
      - camagru_network
    build:
      context: ./api/docker
      dockerfile: ./Dockerfile
      args:
        DB_HOSTNAME: ${DB_HOSTNAME}
        DB_NAME: ${DB_NAME}
        DB_ADMIN: ${DB_ADMIN}
        DB_ADMIN_PASSWD: ${DB_ADMIN_PASSWD}
    image: api
    volumes:
      - ./api/src:/api:ro
    expose:
      - 9000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "nc -z localhost 9000"
      retries: 10
      interval: 2s
