DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS image;

CREATE TABLE user (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(20) UNIQUE NOT NULL,
	CONSTRAINT check_username
	CHECK (username REGEXP '^[a-zA-Z0-9_]{3,20}$')
);

CREATE TABLE post (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	date DATETIME(6),
	user_id INT,
	FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE comment (
	id INT AUTO_INCREMENT PRIMARY KEY,
	date DATETIME(6),
	content VARCHAR(255) NOT NULL,
	user_id INT,
	post_id INT,
	FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE,
	FOREIGN KEY(post_id) REFERENCES post(id) ON DELETE CASCADE
);

CREATE TABLE image (
	id INT AUTO_INCREMENT PRIMARY KEY
);
